# Generated by Django 4.1.3 on 2022-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoqlama',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
    ]
